#include "File.h"
void run() {
	Sleep(1008);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 24, 26), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 24, 27), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 25, 27), MouseEvent::MOVE);
	Sleep(562);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 27, 30), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 28, 32), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 29, 33), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 30, 35), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 32, 37), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 33, 38), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 35, 40), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 39, 43), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 40, 44), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 44, 48), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 45, 48), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 47, 50), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 49, 52), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 50, 53), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 54, 55), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 55, 57), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 57, 58), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 60, 61), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 61, 63), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 64, 67), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 66, 68), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 67, 69), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 70, 71), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 70, 72), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 71, 73), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 72, 75), MouseEvent::MOVE);
	Sleep(32);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 73, 76), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 77, 81), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 78, 83), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 81, 87), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 83, 88), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 87, 91), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 89, 92), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 91, 95), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 95, 99), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 96, 101), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 99, 102), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 102, 105), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 103, 107), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 107, 111), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 111, 113), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 113, 116), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 118, 121), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 122, 124), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 128, 129), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 131, 131), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 135, 134), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 137, 135), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 140, 137), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 143, 139), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 150, 144), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 153, 145), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 159, 148), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 160, 149), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 163, 150), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 166, 153), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 173, 158), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 176, 160), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 183, 166), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 185, 167), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 189, 169), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 191, 170), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 199, 176), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 204, 179), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 213, 188), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 216, 190), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 221, 194), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 223, 196), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 231, 200), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 234, 203), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 236, 204), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 239, 206), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 243, 208), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 247, 210), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 249, 212), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 253, 216), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 255, 218), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 260, 220), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 262, 221), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 265, 223), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 269, 226), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 273, 229), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 275, 230), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 280, 234), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 284, 237), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 291, 243), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 293, 246), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 295, 248), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 304, 255), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 307, 257), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 319, 265), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 322, 269), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 327, 271), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 335, 278), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 340, 280), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 343, 284), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 350, 287), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 358, 292), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 362, 295), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 366, 297), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 375, 304), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 378, 307), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 386, 312), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 391, 314), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 399, 320), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 403, 322), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 408, 324), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 418, 329), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 422, 331), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 428, 334), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 437, 338), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 442, 342), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 452, 347), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 456, 349), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 460, 351), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 469, 356), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 473, 358), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 484, 362), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 489, 364), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 494, 366), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 506, 371), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 511, 373), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 516, 376), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 527, 379), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 531, 382), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 539, 384), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 544, 386), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 548, 388), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 558, 392), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 562, 393), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 572, 398), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 576, 400), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 581, 402), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 591, 407), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 594, 409), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 602, 413), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 606, 415), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 610, 417), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 618, 423), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 623, 425), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 628, 428), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 638, 433), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 642, 434), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 654, 439), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 659, 441), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 665, 443), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 678, 448), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 683, 451), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 694, 456), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 699, 458), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 704, 460), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 715, 466), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 721, 469), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 726, 472), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 738, 478), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 743, 480), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 754, 485), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 760, 489), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 764, 491), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 774, 497), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 779, 499), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 789, 507), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 794, 510), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 799, 514), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 811, 522), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 817, 526), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 829, 534), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 836, 538), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 841, 541), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 855, 548), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 859, 550), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 870, 556), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 876, 559), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 880, 561), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 891, 566), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 896, 568), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 901, 570), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 913, 576), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 918, 579), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 932, 585), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 937, 588), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 943, 589), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 958, 594), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 964, 597), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 980, 602), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 985, 605), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 991, 607), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1004, 609), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1011, 612), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1017, 613), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1028, 617), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1032, 619), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1044, 621), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1048, 622), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1054, 625), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1065, 627), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1071, 628), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1082, 631), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1086, 632), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1091, 632), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1100, 634), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1104, 635), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1108, 636), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1118, 639), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1122, 640), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1132, 644), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1136, 645), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1141, 646), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1150, 650), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1155, 652), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1164, 657), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1169, 658), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1173, 660), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1183, 665), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1187, 668), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1192, 670), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1200, 675), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1204, 676), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1213, 681), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1216, 683), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1227, 687), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1232, 689), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1236, 691), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1246, 696), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1250, 699), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1252, 700), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1259, 703), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1262, 704), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1268, 706), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1269, 707), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1275, 712), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1278, 714), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1280, 715), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1287, 718), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1289, 719), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1294, 723), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1295, 723), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1297, 725), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1301, 727), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1303, 728), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1305, 729), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1310, 731), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1313, 733), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1317, 736), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1319, 737), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1322, 738), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1328, 742), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1330, 743), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1336, 747), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1338, 747), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1339, 748), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1341, 749), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1342, 749), MouseEvent::MOVE);
	Sleep(47);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1343, 749), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1344, 750), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1346, 750), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1347, 751), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1348, 751), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1351, 752), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1352, 752), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1354, 753), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1355, 753), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1355, 754), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1356, 755), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1356, 756), MouseEvent::MOVE);
	Sleep(16);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1357, 757), MouseEvent::MOVE);
	Sleep(15);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1358, 758), MouseEvent::MOVE);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1358, 759), MouseEvent::MOVE);
	Sleep(32);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1358, 760), MouseEvent::MOVE);
	Sleep(125);
	Sender.mouseEvent(MouseCoord(MOUSE_ABSOLUTE, 1359, 760), MouseEvent::MOVE);
}

int main()
{
	//Sleep(1000);
	Logger.record();
	//File.saveMacroCalls("C:/dev/Kengine/Kengine/demo.txt");
	//run();

	//testarr();
	//Logger.printFrames();


	return 0;
}